version: '3.7'

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
