

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1

        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
