
spring:
  data:
    mongodb:
      uri: mongodb+srv://rafaelestrelanotebook:rsCt0bKY2UVUpt5k@cluster0.mli4czt.mongodb.net/test
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

