
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  ssl:
    key-store: certificados/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443